/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoprogramacion;

/**
 *
 * @author orlando
 */
public class VentasInterfaz extends javax.swing.JFrame {

    /**
     * Creates new form VentasInterfaz
     */
    public VentasInterfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSalir = new javax.swing.JButton();
        jLabelSaldoCuenta = new javax.swing.JLabel();
        jLabelDireccion = new javax.swing.JLabel();
        jLabelTipoDePago1 = new javax.swing.JLabel();
        jLabelNumeroCuenta1 = new javax.swing.JLabel();
        jLabelCupon1 = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jLabelBienvenido1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldDireccion = new javax.swing.JTextField();
        jTextFieldTipoDePago = new javax.swing.JTextField();
        jTextFieldNumeroCuenta1 = new javax.swing.JTextField();
        jTextFieldCupon1 = new javax.swing.JTextField();
        jButtonSalir1 = new javax.swing.JButton();
        jTextFieldDineroCuenta = new javax.swing.JTextField();
        jLabelFondo3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSalir.setBackground(new java.awt.Color(238, 236, 153));
        jButtonSalir.setFont(new java.awt.Font("Corbel", 0, 11)); // NOI18N
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, -1, -1));

        jLabelSaldoCuenta.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabelSaldoCuenta.setForeground(new java.awt.Color(102, 98, 68));
        jLabelSaldoCuenta.setText("Saldo de Cuenta");
        getContentPane().add(jLabelSaldoCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 170, 20));

        jLabelDireccion.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabelDireccion.setForeground(new java.awt.Color(102, 98, 68));
        jLabelDireccion.setText("Direccion");
        getContentPane().add(jLabelDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 90, 20));

        jLabelTipoDePago1.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabelTipoDePago1.setForeground(new java.awt.Color(102, 98, 68));
        jLabelTipoDePago1.setText("Tipo de Pago");
        getContentPane().add(jLabelTipoDePago1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 120, 20));

        jLabelNumeroCuenta1.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabelNumeroCuenta1.setForeground(new java.awt.Color(102, 98, 68));
        jLabelNumeroCuenta1.setText("Numero de Cuenta");
        getContentPane().add(jLabelNumeroCuenta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 170, 20));

        jLabelCupon1.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabelCupon1.setForeground(new java.awt.Color(102, 98, 68));
        jLabelCupon1.setText("Cupon");
        getContentPane().add(jLabelCupon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 60, 20));

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LOGO PEQUEÑO (1).png"))); // NOI18N
        getContentPane().add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, -1, -1));

        jLabelBienvenido1.setFont(new java.awt.Font("Corbel", 1, 34)); // NOI18N
        jLabelBienvenido1.setForeground(new java.awt.Color(102, 98, 68));
        jLabelBienvenido1.setText("Datos de Venta");
        getContentPane().add(jLabelBienvenido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 40));

        jLabel1.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 98, 68));
        jLabel1.setText("<html>Por favor digite los datos para continuar con la venta<html>");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 250, 50));

        jTextFieldDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDireccionActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 130, -1));

        jTextFieldTipoDePago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTipoDePagoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldTipoDePago, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 130, -1));

        jTextFieldNumeroCuenta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumeroCuenta1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNumeroCuenta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 130, -1));

        jTextFieldCupon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCupon1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCupon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 130, -1));

        jButtonSalir1.setBackground(new java.awt.Color(238, 236, 153));
        jButtonSalir1.setFont(new java.awt.Font("Corbel", 0, 11)); // NOI18N
        jButtonSalir1.setText("Continuar");
        jButtonSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalir1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, -1, -1));

        jTextFieldDineroCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDineroCuentaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldDineroCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 70, -1));

        jLabelFondo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FONDO.jpg"))); // NOI18N
        jLabelFondo3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelFondo3.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jLabelFondo3ComponentAdded(evt);
            }
        });
        getContentPane().add(jLabelFondo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 425, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelFondo3ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jLabelFondo3ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelFondo3ComponentAdded

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jTextFieldDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDireccionActionPerformed
        Ventas venta1 = new Ventas();
        venta1.setDireccion(jTextFieldDireccion.getText());
    }//GEN-LAST:event_jTextFieldDireccionActionPerformed

    private void jTextFieldTipoDePagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTipoDePagoActionPerformed
        Ventas venta1 = new Ventas();
        venta1.setTipo_de_pago(Integer.parseInt(jTextFieldTipoDePago.getText()));
    }//GEN-LAST:event_jTextFieldTipoDePagoActionPerformed

    private void jTextFieldNumeroCuenta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumeroCuenta1ActionPerformed
        Ventas venta1 = new Ventas();
        venta1.setNum_cuenta(Double.parseDouble(jTextFieldNumeroCuenta1.getText()));
    }//GEN-LAST:event_jTextFieldNumeroCuenta1ActionPerformed

    private void jTextFieldCupon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCupon1ActionPerformed
        Ventas venta1 = new Ventas();
        venta1.setCupon((jTextFieldTipoDePago.getText()));    }//GEN-LAST:event_jTextFieldCupon1ActionPerformed

    private void jButtonSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalir1ActionPerformed
        FacturasInterfaz fact1 = new FacturasInterfaz();
        fact1.setVisible(true);
    }//GEN-LAST:event_jButtonSalir1ActionPerformed

    private void jTextFieldDineroCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDineroCuentaActionPerformed
         Ventas venta1 = new Ventas();
        venta1.setDinero_cuenta(Integer.parseInt(jTextFieldDineroCuenta.getText()));
    }//GEN-LAST:event_jTextFieldDineroCuentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentasInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentasInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentasInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentasInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentasInterfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonSalir1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBienvenido1;
    private javax.swing.JLabel jLabelCupon1;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelFondo3;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelNumeroCuenta1;
    private javax.swing.JLabel jLabelSaldoCuenta;
    private javax.swing.JLabel jLabelTipoDePago1;
    private javax.swing.JTextField jTextFieldCupon1;
    private javax.swing.JTextField jTextFieldDineroCuenta;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldNumeroCuenta1;
    private javax.swing.JTextField jTextFieldTipoDePago;
    // End of variables declaration//GEN-END:variables
}
