/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoprogramacion;

import javax.swing.JOptionPane;

/**
 *
 * @author orlando
 */
public class ClientesInterfaz extends javax.swing.JFrame {

    /**
     * Creates new form Clientes
     */
    public ClientesInterfaz() {
        initComponents();
        
        //Centra la ventana de la interfaz
        this.setLocationRelativeTo(null);
        
       
        
             
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelBienvenido2 = new javax.swing.JLabel();
        jTextField_Nombre = new javax.swing.JTextField();
        jLabelCedula = new javax.swing.JLabel();
        jTextField_Cedula = new javax.swing.JTextField();
        jTextField_Correo = new javax.swing.JTextField();
        jLabelCorreo = new javax.swing.JLabel();
        jTextField_NumContacto = new javax.swing.JTextField();
        jLabelNumContacto = new javax.swing.JLabel();
        jLabelNombre1 = new javax.swing.JLabel();
        jLabelBienvenido1 = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();
        jButtonIniciar = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LOGO.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        jLabelBienvenido2.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabelBienvenido2.setForeground(new java.awt.Color(102, 98, 68));
        jLabelBienvenido2.setText("Para continuar, por favor ingresa los siguientes datos");
        getContentPane().add(jLabelBienvenido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 550, 20));

        jTextField_Nombre.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTextField_Nombre.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField_NombreCaretUpdate(evt);
            }
        });
        jTextField_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_NombreActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 160, 20));

        jLabelCedula.setFont(new java.awt.Font("Corbel", 1, 23)); // NOI18N
        jLabelCedula.setForeground(new java.awt.Color(102, 98, 68));
        jLabelCedula.setText("Cedula");
        getContentPane().add(jLabelCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 90, 20));

        jTextField_Cedula.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTextField_Cedula.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField_CedulaCaretUpdate(evt);
            }
        });
        jTextField_Cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_CedulaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 160, 20));

        jTextField_Correo.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTextField_Correo.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField_CorreoCaretUpdate(evt);
            }
        });
        jTextField_Correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_CorreoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 160, 20));

        jLabelCorreo.setFont(new java.awt.Font("Corbel", 1, 23)); // NOI18N
        jLabelCorreo.setForeground(new java.awt.Color(102, 98, 68));
        jLabelCorreo.setText("Correo");
        getContentPane().add(jLabelCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 90, 20));

        jTextField_NumContacto.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTextField_NumContacto.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField_NumContactoCaretUpdate(evt);
            }
        });
        jTextField_NumContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_NumContactoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_NumContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 160, 20));

        jLabelNumContacto.setFont(new java.awt.Font("Corbel", 1, 23)); // NOI18N
        jLabelNumContacto.setForeground(new java.awt.Color(102, 98, 68));
        jLabelNumContacto.setText("Contacto");
        getContentPane().add(jLabelNumContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 100, 20));

        jLabelNombre1.setFont(new java.awt.Font("Corbel", 1, 23)); // NOI18N
        jLabelNombre1.setForeground(new java.awt.Color(102, 98, 68));
        jLabelNombre1.setText("Nombre");
        getContentPane().add(jLabelNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 90, 20));

        jLabelBienvenido1.setFont(new java.awt.Font("Corbel", 1, 23)); // NOI18N
        jLabelBienvenido1.setForeground(new java.awt.Color(102, 98, 68));
        jLabelBienvenido1.setText("Bienvenido/a a EcoLife");
        getContentPane().add(jLabelBienvenido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 240, 20));

        jButtonSalir.setBackground(new java.awt.Color(238, 236, 153));
        jButtonSalir.setFont(new java.awt.Font("Corbel", 0, 11)); // NOI18N
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 520, -1, -1));

        jButtonIniciar.setBackground(new java.awt.Color(238, 236, 153));
        jButtonIniciar.setFont(new java.awt.Font("Corbel", 0, 11)); // NOI18N
        jButtonIniciar.setText("Iniciar");
        jButtonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FONDO.jpg"))); // NOI18N
        jLabelFondo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray));
        jLabelFondo.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jLabelFondoComponentAdded(evt);
            }
        });
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 425, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_NombreActionPerformed

    private void jTextField_CedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_CedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_CedulaActionPerformed

    private void jTextField_CorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_CorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_CorreoActionPerformed

    private void jTextField_NumContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_NumContactoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_NumContactoActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        //Finalizar el programa
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarActionPerformed
        //Mostrar ventana de productos
       ProductosInterfaz prod = new ProductosInterfaz ();
       prod.setVisible(true);
    }//GEN-LAST:event_jButtonIniciarActionPerformed

    private void jTextField_NombreCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField_NombreCaretUpdate
       //Asigna valor a variable nombre de la clase Clientes
        Clientes client1 = new Clientes();
       client1.setNombre(jTextField_Nombre.getText());
    }//GEN-LAST:event_jTextField_NombreCaretUpdate

    private void jTextField_CedulaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField_CedulaCaretUpdate
       //Asigna valor a variable Cedula de la clase Clientes
        Clientes client1 = new Clientes();
       client1.setCedula(Long.parseLong(jTextField_Cedula.getText()));
    }//GEN-LAST:event_jTextField_CedulaCaretUpdate

    private void jTextField_CorreoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField_CorreoCaretUpdate
       //Asigna valor a variable Correo de la clase Clientes
        Clientes client1 = new Clientes();
       client1.setCorreo(jTextField_Correo.getText());
    }//GEN-LAST:event_jTextField_CorreoCaretUpdate

    private void jTextField_NumContactoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField_NumContactoCaretUpdate
      //Asigna valor a variable Num_contacto de la clase Clientes
        Clientes client1 = new Clientes();
       client1.setNum_contacto(Long.parseLong(jTextField_NumContacto.getText())); 
    }//GEN-LAST:event_jTextField_NumContactoCaretUpdate

    private void jLabelFondoComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jLabelFondoComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelFondoComponentAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientesInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientesInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientesInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientesInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientesInterfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIniciar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBienvenido1;
    private javax.swing.JLabel jLabelBienvenido2;
    private javax.swing.JLabel jLabelCedula;
    private javax.swing.JLabel jLabelCorreo;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelNombre1;
    private javax.swing.JLabel jLabelNumContacto;
    private javax.swing.JTextField jTextField_Cedula;
    private javax.swing.JTextField jTextField_Correo;
    private javax.swing.JTextField jTextField_Nombre;
    private javax.swing.JTextField jTextField_NumContacto;
    // End of variables declaration//GEN-END:variables
}
