/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoprogramacion;

import javax.swing.JOptionPane;

/**
 *
 * @author Familia Cortes Moren
 */
public class FacturasInterfaz extends javax.swing.JFrame {

    /**
     * Creates new form FacturasInterfaz
     */
    public FacturasInterfaz() {
        initComponents();
        //Centrar ventana de la interfaz Facturas
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLogo = new javax.swing.JLabel();
        jLabelFacturadeVenta = new javax.swing.JLabel();
        jLabelDescripción = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();
        jButtonRealizarPago = new javax.swing.JButton();
        jLabelFondo4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LOGO PEQUEÑO (1).png"))); // NOI18N
        getContentPane().add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, -1, -1));

        jLabelFacturadeVenta.setFont(new java.awt.Font("Corbel", 1, 34)); // NOI18N
        jLabelFacturadeVenta.setForeground(new java.awt.Color(102, 98, 68));
        jLabelFacturadeVenta.setText("Factura de Venta");
        getContentPane().add(jLabelFacturadeVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 40));

        jLabelDescripción.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabelDescripción.setForeground(new java.awt.Color(102, 98, 68));
        jLabelDescripción.setText("<html>Por favor ingrese el dato de la fecha, observe la información de la compra<html>");
        getContentPane().add(jLabelDescripción, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 280, 60));

        jButtonSalir.setBackground(new java.awt.Color(238, 236, 153));
        jButtonSalir.setFont(new java.awt.Font("Corbel", 0, 11)); // NOI18N
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, -1, -1));

        jButtonRealizarPago.setBackground(new java.awt.Color(238, 236, 153));
        jButtonRealizarPago.setFont(new java.awt.Font("Corbel", 0, 11)); // NOI18N
        jButtonRealizarPago.setText("Pagar");
        jButtonRealizarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRealizarPagoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRealizarPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabelFondo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FONDO.jpg"))); // NOI18N
        jLabelFondo4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray));
        jLabelFondo4.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jLabelFondo4ComponentAdded(evt);
            }
        });
        getContentPane().add(jLabelFondo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelFondo4ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jLabelFondo4ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelFondo4ComponentAdded

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
      //Finalizar el programa
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonRealizarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRealizarPagoActionPerformed
    //Metodo Realizar Pago
       Facturas factura1 = new Facturas();
       factura1.setFecha_compra(JOptionPane.showInputDialog ("Digite la Fecha de la Compra"));
       factura1.mostrar_factura();
     
    }//GEN-LAST:event_jButtonRealizarPagoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacturasInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacturasInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacturasInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacturasInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FacturasInterfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRealizarPago;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelDescripción;
    private javax.swing.JLabel jLabelFacturadeVenta;
    private javax.swing.JLabel jLabelFondo4;
    private javax.swing.JLabel jLabelLogo;
    // End of variables declaration//GEN-END:variables
}
