/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoprogramacion;

import javax.swing.JOptionPane;

/**
 *
 * @author orlando
 */
public class InterfazVentas extends javax.swing.JFrame {

    /**
     * Creates new form InterfazVentas
     */
    public InterfazVentas() {
        initComponents();
        //Centrar ventana de la interfaz de Ventas
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFacturadeVenta = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jLabelDescripción = new javax.swing.JLabel();
        jLabelMontoCuenta = new javax.swing.JLabel();
        jLabelCupon = new javax.swing.JLabel();
        jLabelNumeroCuenta = new javax.swing.JLabel();
        jLabelDireccion = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();
        jTextField_Direccion = new javax.swing.JTextField();
        jTextField_NumeroCuenta = new javax.swing.JTextField();
        jTextField_Cupon = new javax.swing.JTextField();
        jTextField_SaldoCuenta = new javax.swing.JTextField();
        jButtonRealizarPago = new javax.swing.JButton();
        jButtonAplicarCupon = new javax.swing.JButton();
        jLabelFacturadeVenta1 = new javax.swing.JLabel();
        jLabelFondo4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelFacturadeVenta.setFont(new java.awt.Font("Corbel", 1, 34)); // NOI18N
        jLabelFacturadeVenta.setForeground(new java.awt.Color(102, 98, 68));
        jLabelFacturadeVenta.setText("Datos de Venta");
        getContentPane().add(jLabelFacturadeVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 40));

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LOGO PEQUEÑO (1).png"))); // NOI18N
        getContentPane().add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, -1, -1));

        jLabelDescripción.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabelDescripción.setForeground(new java.awt.Color(102, 98, 68));
        jLabelDescripción.setText("<html>Por favor ingrese los siguientes datos para continuar con el pago<html>");
        getContentPane().add(jLabelDescripción, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 280, 60));

        jLabelMontoCuenta.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabelMontoCuenta.setForeground(new java.awt.Color(102, 98, 68));
        jLabelMontoCuenta.setText("Saldo Cuenta");
        getContentPane().add(jLabelMontoCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 140, 20));

        jLabelCupon.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabelCupon.setForeground(new java.awt.Color(102, 98, 68));
        jLabelCupon.setText("Cupon");
        getContentPane().add(jLabelCupon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 90, 20));

        jLabelNumeroCuenta.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabelNumeroCuenta.setForeground(new java.awt.Color(102, 98, 68));
        jLabelNumeroCuenta.setText("Numero de Cuenta");
        getContentPane().add(jLabelNumeroCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 170, 20));

        jLabelDireccion.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabelDireccion.setForeground(new java.awt.Color(102, 98, 68));
        jLabelDireccion.setText("Direccion");
        getContentPane().add(jLabelDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 90, 20));

        jButtonSalir.setBackground(new java.awt.Color(238, 236, 153));
        jButtonSalir.setFont(new java.awt.Font("Corbel", 0, 11)); // NOI18N
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, -1, -1));

        jTextField_Direccion.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField_DireccionCaretUpdate(evt);
            }
        });
        jTextField_Direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_DireccionActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 120, -1));

        jTextField_NumeroCuenta.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField_NumeroCuentaCaretUpdate(evt);
            }
        });
        getContentPane().add(jTextField_NumeroCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 100, -1));

        jTextField_Cupon.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField_CuponCaretUpdate(evt);
            }
        });
        getContentPane().add(jTextField_Cupon, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 100, -1));

        jTextField_SaldoCuenta.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField_SaldoCuentaCaretUpdate(evt);
            }
        });
        getContentPane().add(jTextField_SaldoCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 100, -1));

        jButtonRealizarPago.setBackground(new java.awt.Color(238, 236, 153));
        jButtonRealizarPago.setFont(new java.awt.Font("Corbel", 0, 11)); // NOI18N
        jButtonRealizarPago.setText("Realizar Pago");
        jButtonRealizarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRealizarPagoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRealizarPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, -1, -1));

        jButtonAplicarCupon.setBackground(new java.awt.Color(238, 236, 153));
        jButtonAplicarCupon.setFont(new java.awt.Font("Corbel", 0, 11)); // NOI18N
        jButtonAplicarCupon.setText("Aplicar Cupon");
        jButtonAplicarCupon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAplicarCuponActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAplicarCupon, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        jLabelFacturadeVenta1.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabelFacturadeVenta1.setForeground(new java.awt.Color(102, 98, 68));
        jLabelFacturadeVenta1.setText("(MAYUSCULAS)");
        getContentPane().add(jLabelFacturadeVenta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, 40));

        jLabelFondo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FONDO.jpg"))); // NOI18N
        jLabelFondo4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray));
        jLabelFondo4.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jLabelFondo4ComponentAdded(evt);
            }
        });
        getContentPane().add(jLabelFondo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 425, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelFondo4ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jLabelFondo4ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelFondo4ComponentAdded

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        //Finalizar el programa 
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonRealizarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRealizarPagoActionPerformed
        //Mostrar la interfaz de Facturas
        FacturasInterfaz fact1 = new FacturasInterfaz();
        fact1.setVisible(true);
    }//GEN-LAST:event_jButtonRealizarPagoActionPerformed

    private void jTextField_DireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_DireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_DireccionActionPerformed

    private void jTextField_DireccionCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField_DireccionCaretUpdate
       //Dar valor al atributo Direccion de la clase VentasProducts
       VentasProducts vent1 = new VentasProducts();
       vent1.setDireccion(jTextField_Direccion.getText());
    }//GEN-LAST:event_jTextField_DireccionCaretUpdate

    private void jTextField_NumeroCuentaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField_NumeroCuentaCaretUpdate
       //Dar valor al atributo Num Cuenta de la clase VentasProducts
       VentasProducts vent1 = new VentasProducts();
       vent1.setNum_cuenta(Double.parseDouble(jTextField_NumeroCuenta.getText()));
    }//GEN-LAST:event_jTextField_NumeroCuentaCaretUpdate

    private void jTextField_CuponCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField_CuponCaretUpdate
       //Dar valor al atributo Cupon de la clase VentasProducts
       VentasProducts vent1 = new VentasProducts();
       vent1.setCupon(jTextField_Cupon.getText());
    }//GEN-LAST:event_jTextField_CuponCaretUpdate

    private void jTextField_SaldoCuentaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField_SaldoCuentaCaretUpdate
       //Dar valor al atributo Monto Cuenta de la clase VentasProducts
       VentasProducts vent1 = new VentasProducts();
       vent1.setMonto_cuenta(Double.parseDouble(jTextField_SaldoCuenta.getText()));
    }//GEN-LAST:event_jTextField_SaldoCuentaCaretUpdate

    private void jButtonAplicarCuponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAplicarCuponActionPerformed
      //Metodo Aplicar Cupon
       VentasProducts vent1 = new VentasProducts();
       Productos product1 = new Productos();
       
       if ("VERANO".equals(vent1.getCupon()))
       {
            product1.setPrecio_total(product1.getPrecio_total() - (product1.getPrecio_total()*0.2));
            JOptionPane.showMessageDialog(null, "Aplicando el descuento de VERANO, tiene un descuento del 20%."
                    + " El nuevo valor total de su compra es: " + product1.getPrecio_total());

       }
    }//GEN-LAST:event_jButtonAplicarCuponActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazVentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAplicarCupon;
    private javax.swing.JButton jButtonRealizarPago;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelCupon;
    private javax.swing.JLabel jLabelDescripción;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelFacturadeVenta;
    private javax.swing.JLabel jLabelFacturadeVenta1;
    private javax.swing.JLabel jLabelFondo4;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelMontoCuenta;
    private javax.swing.JLabel jLabelNumeroCuenta;
    private javax.swing.JTextField jTextField_Cupon;
    private javax.swing.JTextField jTextField_Direccion;
    private javax.swing.JTextField jTextField_NumeroCuenta;
    private javax.swing.JTextField jTextField_SaldoCuenta;
    // End of variables declaration//GEN-END:variables
}
