/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoprogramacion;

import javax.swing.JOptionPane;

/**
 *
 * @author orlando
 */
public class ProductosInterfaz extends javax.swing.JFrame {

    /**
     * Creates new form Productos
     */
    public ProductosInterfaz() {
        initComponents();
        //Centrar la ventana de la interfaz
        this.setLocationRelativeTo(null);
       
        //Llamar Variable nombre de la clase Clientes y mostrar al abrir interfaz de productos
       Clientes client1 = new Clientes();
       JOptionPane.showMessageDialog(null, "Bienvenido/a " + client1.getNombre());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();
        jLabelCantidad = new javax.swing.JLabel();
        jLabelPrecioUnitario = new javax.swing.JLabel();
        jLabelNombreP1 = new javax.swing.JLabel();
        jLabelNombrep = new javax.swing.JLabel();
        jLabelBienvenido1 = new javax.swing.JLabel();
        jLabelBienvenido2 = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jTextFieldCantidadP = new javax.swing.JTextField();
        jTextField_CodigoP = new javax.swing.JTextField();
        jTextField_NombreP = new javax.swing.JTextField();
        jTextField_PrecioP = new javax.swing.JTextField();
        jLabelProducto1 = new javax.swing.JLabel();
        jLabelProducto2 = new javax.swing.JLabel();
        jLabelProducto3 = new javax.swing.JLabel();
        jLabelProducto4 = new javax.swing.JLabel();
        jButtonAgregarProducto = new javax.swing.JButton();
        jButtonRegistrarComprar = new javax.swing.JButton();
        jButtonEliminarProducto = new javax.swing.JButton();
        jLabelCodigop2 = new javax.swing.JLabel();
        jLabelPrecioP1 = new javax.swing.JLabel();
        jLabelCodigoP1 = new javax.swing.JLabel();
        jLabelNombreP3 = new javax.swing.JLabel();
        jLabelCodigoP3 = new javax.swing.JLabel();
        jLabelPrecioP3 = new javax.swing.JLabel();
        jLabelNombreP4 = new javax.swing.JLabel();
        jLabelCodigoP4 = new javax.swing.JLabel();
        jLabelPrecioP4 = new javax.swing.JLabel();
        jLabelNombreP2 = new javax.swing.JLabel();
        jLabelCodigoP2 = new javax.swing.JLabel();
        jLabelPrecioP2 = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSalir.setBackground(new java.awt.Color(238, 236, 153));
        jButtonSalir.setFont(new java.awt.Font("Corbel", 0, 11)); // NOI18N
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 520, -1, -1));

        jLabelCantidad.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabelCantidad.setForeground(new java.awt.Color(102, 98, 68));
        jLabelCantidad.setText("Cantidad");
        getContentPane().add(jLabelCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 90, 20));

        jLabelPrecioUnitario.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabelPrecioUnitario.setForeground(new java.awt.Color(102, 98, 68));
        jLabelPrecioUnitario.setText("Precio");
        getContentPane().add(jLabelPrecioUnitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 90, 20));

        jLabelNombreP1.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabelNombreP1.setForeground(new java.awt.Color(102, 98, 68));
        jLabelNombreP1.setText("<html>Rasuradora Metalica<html>");
        getContentPane().add(jLabelNombreP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 90, 50));

        jLabelNombrep.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabelNombrep.setForeground(new java.awt.Color(102, 98, 68));
        jLabelNombrep.setText("Nombre");
        getContentPane().add(jLabelNombrep, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 90, 20));

        jLabelBienvenido1.setFont(new java.awt.Font("Corbel", 1, 34)); // NOI18N
        jLabelBienvenido1.setForeground(new java.awt.Color(102, 98, 68));
        jLabelBienvenido1.setText("PRODUCTOS");
        getContentPane().add(jLabelBienvenido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 40));

        jLabelBienvenido2.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabelBienvenido2.setForeground(new java.awt.Color(102, 98, 68));
        jLabelBienvenido2.setText("<html>Por favor, ingrese los datos de los productos que desea comprar <html>");
        getContentPane().add(jLabelBienvenido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 280, 60));

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LOGO PEQUEÑO (1).png"))); // NOI18N
        getContentPane().add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, -1, -1));

        jTextFieldCantidadP.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTextFieldCantidadP.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextFieldCantidadPCaretUpdate(evt);
            }
        });
        getContentPane().add(jTextFieldCantidadP, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 120, 20));

        jTextField_CodigoP.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTextField_CodigoP.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField_CodigoPCaretUpdate(evt);
            }
        });
        getContentPane().add(jTextField_CodigoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 120, 20));

        jTextField_NombreP.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTextField_NombreP.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField_NombrePCaretUpdate(evt);
            }
        });
        getContentPane().add(jTextField_NombreP, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 120, 20));

        jTextField_PrecioP.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTextField_PrecioP.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField_PrecioPCaretUpdate(evt);
            }
        });
        getContentPane().add(jTextField_PrecioP, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 120, 20));

        jLabelProducto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Eco Razor (3).jpg"))); // NOI18N
        jLabelProducto1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 98, 68), 4));
        getContentPane().add(jLabelProducto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jLabelProducto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Kits de Cubiertos Bambu.jpg"))); // NOI18N
        jLabelProducto2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 98, 68), 4));
        getContentPane().add(jLabelProducto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, -1, -1));

        jLabelProducto3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Tapas Silicona.jpg"))); // NOI18N
        jLabelProducto3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 98, 68), 4));
        getContentPane().add(jLabelProducto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        jLabelProducto4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Termo Plegable de Silicona.jpg"))); // NOI18N
        jLabelProducto4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 98, 68), 4));
        getContentPane().add(jLabelProducto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, -1, -1));

        jButtonAgregarProducto.setBackground(new java.awt.Color(238, 236, 153));
        jButtonAgregarProducto.setFont(new java.awt.Font("Corbel", 0, 11)); // NOI18N
        jButtonAgregarProducto.setText("Agregar Producto");
        jButtonAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarProductoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgregarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 140, -1));

        jButtonRegistrarComprar.setBackground(new java.awt.Color(238, 236, 153));
        jButtonRegistrarComprar.setFont(new java.awt.Font("Corbel", 0, 11)); // NOI18N
        jButtonRegistrarComprar.setText("Registrar Compra");
        jButtonRegistrarComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarComprarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegistrarComprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 140, -1));

        jButtonEliminarProducto.setBackground(new java.awt.Color(238, 236, 153));
        jButtonEliminarProducto.setFont(new java.awt.Font("Corbel", 0, 11)); // NOI18N
        jButtonEliminarProducto.setText("Eliminar Producto");
        jButtonEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarProductoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEliminarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 140, -1));

        jLabelCodigop2.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabelCodigop2.setForeground(new java.awt.Color(102, 98, 68));
        jLabelCodigop2.setText("Codigo");
        getContentPane().add(jLabelCodigop2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 90, 20));

        jLabelPrecioP1.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabelPrecioP1.setForeground(new java.awt.Color(102, 98, 88));
        jLabelPrecioP1.setText("Precio: $1800");
        getContentPane().add(jLabelPrecioP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, -1, -1));

        jLabelCodigoP1.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabelCodigoP1.setForeground(new java.awt.Color(102, 98, 88));
        jLabelCodigoP1.setText("Codigo: 1");
        getContentPane().add(jLabelCodigoP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, -1, -1));

        jLabelNombreP3.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabelNombreP3.setForeground(new java.awt.Color(102, 98, 68));
        jLabelNombreP3.setText("<html>Tapas de Plastico Reutilizables<html>");
        getContentPane().add(jLabelNombreP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 110, 50));

        jLabelCodigoP3.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabelCodigoP3.setForeground(new java.awt.Color(102, 98, 88));
        jLabelCodigoP3.setText("Codigo: 3");
        getContentPane().add(jLabelCodigoP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, -1, -1));

        jLabelPrecioP3.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabelPrecioP3.setForeground(new java.awt.Color(102, 98, 88));
        jLabelPrecioP3.setText("Precio: $5000");
        getContentPane().add(jLabelPrecioP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, -1, -1));

        jLabelNombreP4.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabelNombreP4.setForeground(new java.awt.Color(102, 98, 68));
        jLabelNombreP4.setText("<html>Termos Plegables<html>");
        getContentPane().add(jLabelNombreP4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 110, 50));

        jLabelCodigoP4.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabelCodigoP4.setForeground(new java.awt.Color(102, 98, 88));
        jLabelCodigoP4.setText("Codigo: 4");
        getContentPane().add(jLabelCodigoP4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, -1, -1));

        jLabelPrecioP4.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabelPrecioP4.setForeground(new java.awt.Color(102, 98, 88));
        jLabelPrecioP4.setText("Precio: $7000");
        getContentPane().add(jLabelPrecioP4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 480, -1, -1));

        jLabelNombreP2.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabelNombreP2.setForeground(new java.awt.Color(102, 98, 68));
        jLabelNombreP2.setText("<html>Set Cubiertos Bambu<html>");
        getContentPane().add(jLabelNombreP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 90, 50));

        jLabelCodigoP2.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabelCodigoP2.setForeground(new java.awt.Color(102, 98, 88));
        jLabelCodigoP2.setText("Codigo: 2");
        getContentPane().add(jLabelCodigoP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, -1, -1));

        jLabelPrecioP2.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabelPrecioP2.setForeground(new java.awt.Color(102, 98, 88));
        jLabelPrecioP2.setText("Precio: $10500");
        getContentPane().add(jLabelPrecioP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FONDO.jpg"))); // NOI18N
        jLabelFondo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray));
        jLabelFondo.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jLabelFondoComponentAdded(evt);
            }
        });
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 425, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelFondoComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jLabelFondoComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelFondoComponentAdded

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        //Finalizar el programa
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarProductoActionPerformed

    //Metodo Agregar Productos 
        Productos product1 = new Productos();
        if(product1.getCodigo() == 1)
        {
          
          product1.setPrecio_a_pagar(product1.getCantidadp()* product1.getPrecio_unitario());
          product1.setPrecio_total(product1.getPrecio_total()+product1.getPrecio_a_pagar());
          JOptionPane.showMessageDialog(null, "El valor total de su compra es: " + product1.getPrecio_total());
          
        }
        else if (product1.getCodigo()==2)
        {
          product1.setPrecio_a_pagar(product1.getCantidadp()* product1.getPrecio_unitario());
          product1.setPrecio_total(product1.getPrecio_total()+product1.getPrecio_a_pagar());
          JOptionPane.showMessageDialog(null, "El valor total de su compra es: " + product1.getPrecio_total());           
        }
        else if (product1.getCodigo()==3)
        {
          product1.setPrecio_a_pagar(product1.getCantidadp()* product1.getPrecio_unitario());
          product1.setPrecio_total(product1.getPrecio_total()+product1.getPrecio_a_pagar());
          JOptionPane.showMessageDialog(null, "El valor total de su compra es: " + product1.getPrecio_total());   
        }
        else if (product1.getCodigo()==4)
        {
          product1.setPrecio_a_pagar(product1.getCantidadp()* product1.getPrecio_unitario());
          product1.setPrecio_total(product1.getPrecio_total()+product1.getPrecio_a_pagar());
          JOptionPane.showMessageDialog(null, "El valor total de su compra es: " + product1.getPrecio_total());   
        }
        else
        {
         JOptionPane.showMessageDialog(null, "El codigo es incorrecto");
        }
    }//GEN-LAST:event_jButtonAgregarProductoActionPerformed

    private void jButtonRegistrarComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarComprarActionPerformed
        //Mostrar interfaz de Ventas
        InterfazVentas vent = new InterfazVentas ();
        vent.setVisible(true);
    }//GEN-LAST:event_jButtonRegistrarComprarActionPerformed

    private void jButtonEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarProductoActionPerformed
        //Metodo Eliminar Productos 
        Productos product1 = new Productos();
        if(product1.getCodigo() == 1 || product1.getCodigo()== 2 || product1.getCodigo()== 3 || product1.getCodigo()== 4)
        {
          
          product1.setPrecio_total(product1.getPrecio_total()-product1.getPrecio_unitario());
          
          JOptionPane.showMessageDialog(null, "El valor total de su compra es: " + product1.getPrecio_total());
          
        }
    }//GEN-LAST:event_jButtonEliminarProductoActionPerformed

    private void jTextField_CodigoPCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField_CodigoPCaretUpdate
       //Dar valor a la variable CodigoP de la clase Productos
       Productos product1 = new Productos();
       product1.setCodigo(Double.parseDouble(jTextField_CodigoP.getText()));
    }//GEN-LAST:event_jTextField_CodigoPCaretUpdate

    private void jTextField_NombrePCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField_NombrePCaretUpdate
       //Dar valor a la variable NombreP de la clase Productos
       Productos product1 = new Productos();
       product1.setNombrep(jTextField_NombreP.getText());
    }//GEN-LAST:event_jTextField_NombrePCaretUpdate

    private void jTextField_PrecioPCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField_PrecioPCaretUpdate
       //Dar valor a la variable PrecioP de la clase Productos
       Productos product1 = new Productos();
       product1.setPrecio_unitario(Double.parseDouble(jTextField_PrecioP.getText()));
    }//GEN-LAST:event_jTextField_PrecioPCaretUpdate

    private void jTextFieldCantidadPCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextFieldCantidadPCaretUpdate
       //Dar valor a la variable CantidadP de la clase Productos
       Productos product1 = new Productos();
       product1.setCantidadp(Double.parseDouble(jTextFieldCantidadP.getText()));
    }//GEN-LAST:event_jTextFieldCantidadPCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductosInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductosInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductosInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductosInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductosInterfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarProducto;
    private javax.swing.JButton jButtonEliminarProducto;
    private javax.swing.JButton jButtonRegistrarComprar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBienvenido1;
    private javax.swing.JLabel jLabelBienvenido2;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelCodigoP1;
    private javax.swing.JLabel jLabelCodigoP2;
    private javax.swing.JLabel jLabelCodigoP3;
    private javax.swing.JLabel jLabelCodigoP4;
    private javax.swing.JLabel jLabelCodigop2;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelNombreP1;
    private javax.swing.JLabel jLabelNombreP2;
    private javax.swing.JLabel jLabelNombreP3;
    private javax.swing.JLabel jLabelNombreP4;
    private javax.swing.JLabel jLabelNombrep;
    private javax.swing.JLabel jLabelPrecioP1;
    private javax.swing.JLabel jLabelPrecioP2;
    private javax.swing.JLabel jLabelPrecioP3;
    private javax.swing.JLabel jLabelPrecioP4;
    private javax.swing.JLabel jLabelPrecioUnitario;
    private javax.swing.JLabel jLabelProducto1;
    private javax.swing.JLabel jLabelProducto2;
    private javax.swing.JLabel jLabelProducto3;
    private javax.swing.JLabel jLabelProducto4;
    private javax.swing.JTextField jTextFieldCantidadP;
    private javax.swing.JTextField jTextField_CodigoP;
    private javax.swing.JTextField jTextField_NombreP;
    public javax.swing.JTextField jTextField_PrecioP;
    // End of variables declaration//GEN-END:variables
}
